import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

async function main() {
  const uploadsDir = path.join(__dirname, '..', 'backend', 'uploads');
  const sampleFile = '1786336632633-d6063b33-5067-4f5f-8297-5625d1ffbbce.png';
  const imagePath = path.join(uploadsDir, sampleFile);

  console.log(`[E2E-TEST] Reading file: ${sampleFile}`);
  const fileBuffer = fs.readFileSync(imagePath);
  const blob = new Blob([fileBuffer], { type: 'image/png' });

  const formData = new FormData();
  formData.append('file', blob, 'visitor_handwritten_test.png');
  formData.append('documentTypeId', 'dt-visitor');

  console.log('[E2E-TEST] Uploading to http://localhost:3000/api/documents/upload ...');

  const res = await fetch('http://localhost:3000/api/documents/upload', {
    method: 'POST',
    body: formData
  });

  const json = await res.json();
  console.log('\n[E2E-TEST] Upload HTTP Status:', res.status);
  console.log('[E2E-TEST] Success:', json.success);

  if (json.data && json.data.document) {
    const docId = json.data.document.id;
    console.log(`\n[E2E-TEST] Document ID: ${docId}`);
    console.log(`[E2E-TEST] Extracted Fields Count: ${json.data.extractedFields?.length}`);
    
    if (json.data.extractedFields) {
      console.log('\n--- EXTRACTED FIELDS FROM REAL OCR PIPELINE ---');
      json.data.extractedFields.forEach(f => {
        console.log(`  ✓ ${f.fieldKey.padEnd(20)}: ocrValue="${f.ocrValue}" confidence=${f.confidence} isValid=${f.isValid}`);
      });
    }

    // Check debug crop directory generated by backend server
    const debugDir = path.join(__dirname, '..', 'backend', 'debug-crops', docId);
    if (fs.existsSync(debugDir)) {
      console.log(`\n[E2E-TEST] Debug crops generated on disk: ${debugDir}`);
      const cropFiles = fs.readdirSync(debugDir);
      cropFiles.forEach(f => {
        const size = fs.statSync(path.join(debugDir, f)).size;
        console.log(`  - ${f.padEnd(25)} (${size} bytes)`);
      });
    }
  } else {
    console.error('[E2E-TEST] Upload failed:', json.error);
  }
}

main().catch(console.error);
